#!/bin/bash

# Check enrollments data in Supabase
# This script helps verify if the pricing fields are properly populated

echo "=== Enrollment Pricing Data Check ==="
echo ""
echo "Run this query in Supabase SQL Editor to check enrollments data:"
echo ""
echo "-- Check sample enrollments with pricing data"
echo "SELECT "
echo "  id,"
echo "  user_id,"
echo "  course_id,"
echo "  payment_status,"
echo "  enrolled_price,"
echo "  enrolled_original_price,"
echo "  enrolled_at,"
echo "  created_at"
echo "FROM enrollments"
echo "LIMIT 10;"
echo ""
echo "-- Count enrollments with pricing data"
echo "SELECT "
echo "  COUNT(*) as total_enrollments,"
echo "  COUNT(enrolled_price) as with_enrolled_price,"
echo "  COUNT(enrolled_original_price) as with_enrolled_original_price,"
echo "  COUNT(CASE WHEN enrolled_price IS NULL OR enrolled_original_price IS NULL THEN 1 END) as missing_pricing"
echo "FROM enrollments;"
echo ""
echo "-- Check paid enrollments and their total revenue"
echo "SELECT "
echo "  COUNT(*) as paid_enrollments,"
echo "  SUM(enrolled_original_price) as total_original_price,"
echo "  SUM(enrolled_price) as total_paid_price"
echo "FROM enrollments"
echo "WHERE payment_status = 'paid';"
echo ""
echo "-- Check which courses have enrollments with pricing"
echo "SELECT "
echo "  c.id,"
echo "  c.title,"
echo "  COUNT(e.id) as enrollment_count,"
echo "  SUM(e.enrolled_original_price) as total_revenue"
echo "FROM courses c"
echo "LEFT JOIN enrollments e ON c.id = e.course_id AND e.payment_status = 'paid'"
echo "GROUP BY c.id, c.title"
echo "ORDER BY total_revenue DESC;"
