import type { PartnerProgram } from './types';

const mastersMarketingLearnPoints = [
  'Master marketing strategy, branding, and consumer behaviour',
  'Apply digital marketing, analytics, and campaign planning skills',
  'Develop go-to-market and sales enablement capabilities',
  'Build credentials for marketing leadership and growth roles',
];

const salesMarketingLearnPoints = [
  'Strengthen sales strategy, negotiation, and account management skills',
  'Apply marketing frameworks to drive revenue and customer growth',
  'Lead go-to-market initiatives across channels and segments',
  'Build credentials for sales and marketing leadership roles',
];

const bachelorsMarketingLearnPoints = [
  'Build a foundation in marketing strategy, branding, and consumer behaviour',
  'Apply digital marketing, analytics, and campaign planning skills',
  'Develop communication and go-to-market capabilities',
  'Prepare for entry-level marketing and business roles',
];

export const marketingPrograms: PartnerProgram[] = [
  // —— Master's programmes ——
  {
    id: 'marketing-chandigarh-university-1',
    title: 'Online MBA in Marketing – Chandigarh University',
    description:
      'Online MBA programme in Marketing from Chandigarh University. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'Chandigarh University',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/chandigarh-university/online-mba-in-marketing?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'rose',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-jain-university-2',
    title: 'Online MBA in Marketing – Jain University',
    description:
      'Online MBA programme in Marketing from Jain University. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'Jain University',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/jain-university/online-mba-in-marketing?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'emerald',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-vit-3',
    title: 'VIT Online MBA – Marketing',
    description:
      'Online MBA programme in Marketing from VIT. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'VIT',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/vit/vit-online-mba-marketing?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'indigo',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-lovely-professional-university-4',
    title: 'Online MBA in Marketing – LPU',
    description:
      'Online MBA programme in Marketing from Lovely Professional University. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'Lovely Professional University',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/lovely-professional-university/online-mba-in-marketing-lpu?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'amber',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-sharda-university-5',
    title: 'Online MBA Marketing – Sharda Online',
    description:
      'Online MBA programme in Marketing from Sharda University. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'Sharda University',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/sharda-university/online-mba-marketing-sharda-online?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'blue',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-iim-indore-advanced-6',
    title: 'Advanced Marketing Management – IIM Indore',
    description:
      'Executive programme in Marketing from IIM Indore. Designed for intermediate professionals seeking advanced marketing management skills with flexible online learning.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'IIM Indore',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/iim-indore/advanced-marketing-management-iim-indore?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'rose',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-iim-calcutta-advanced-7',
    title: 'Advanced Programme for Marketing Professionals – IIM Calcutta',
    description:
      'Executive programme in Marketing from IIM Calcutta. Designed for intermediate professionals seeking advanced marketing management skills with flexible online learning.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'IIM Calcutta',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/iim-calcutta/advanced-programme-for-marketing-professionals?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'rose',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-nmims-8',
    title: 'MBA in Marketing Management – NMIMS CDOE',
    description:
      'Online MBA programme in Marketing Management from NMIMS. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'NMIMS',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/nmims/mba-in-marketing-management-nmims-cdoe?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'purple',
    specialization: 'Marketing Management',
    degreeType: 'masters',
  },
  {
    id: 'marketing-dy-patil-university-pune-9',
    title: 'Online MBA Marketing Management – DPU-COL',
    description:
      'Online MBA programme in Marketing Management from DY Patil University, Pune. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'DY Patil University, Pune',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/dy-patil-university-pune/online-mba-marketing-management-dpucol?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'cyan',
    specialization: 'Marketing Management',
    degreeType: 'masters',
  },
  {
    id: 'marketing-amrita-university-10',
    title: 'Online MBA in Marketing – Amrita University',
    description:
      'Online MBA programme in Marketing from Amrita University. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'Amrita University',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/amrita-university/online-mba-in-marketing-amrita-university?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'fuchsia',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-kj-somaiya-11',
    title: 'K.J. Somaiya MBA in Marketing Management',
    description:
      'Online MBA programme in Marketing Management from K. J. Somaiya Institute of Management. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'K. J. Somaiya Institute of Management',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/k-j-somaiya-institute-of-management/kj-somaiya-mba-in-marketing-management?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'rose',
    specialization: 'Marketing Management',
    degreeType: 'masters',
  },
  {
    id: 'marketing-vignan-university-12',
    title: 'Online MBA in Marketing – Vignan Online',
    description:
      'Online MBA programme in Marketing from Vignan University. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'Vignan University',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/vignan-university/online-mba-in-marketing-vignan-online?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'sky',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-iim-calcutta-sales-13',
    title: 'Sales & Marketing Executive Programme – IIM Calcutta',
    description:
      'Executive programme in Sales & Marketing from IIM Calcutta. Designed for intermediate professionals seeking advanced sales and marketing skills with flexible online learning.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'IIM Calcutta',
    learnPoints: salesMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/iim-calcutta/sales-marketing-executive-programme-iim-calcutta?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'rose',
    specialization: 'Sales & Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-alliance-university-14',
    title: 'Alliance University Online MBA in Marketing',
    description:
      'Online MBA programme in Marketing from Alliance University. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'Alliance University',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/alliance-university/alliance-university-online-mba-in-marketing?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'violet',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-nmims-wx-15',
    title: 'MBA (WX) – Marketing Management – NMIMS CDOE Online',
    description:
      'Online MBA (Work-Ex) programme in Marketing Management from NMIMS. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'NMIMS',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/nmims/mba-wx-marketing-management-nmims-cdoe-online?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'purple',
    specialization: 'Marketing Management',
    degreeType: 'masters',
  },
  {
    id: 'marketing-manipal-university-jaipur-16',
    title: 'Online MBA in Marketing – Manipal University Jaipur',
    description:
      'Online MBA programme in Marketing from Manipal University Jaipur. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'Manipal University Jaipur',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/manipal-university-jaipur/online-mba-in-marketing-manipal-university-jaipur?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'orange',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-kl-university-17',
    title: 'MBA in Marketing Online Degree – KLU Online',
    description:
      'Online MBA programme in Marketing from KL University. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'KL University',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/kl-university/mba-in-marketing-online-degree-klu-online?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'teal',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-iim-indore-sales-18',
    title: 'Sales and Marketing Executive Programme – IIM Indore',
    description:
      'Executive programme in Sales & Marketing from IIM Indore. Designed for intermediate professionals seeking advanced sales and marketing skills with flexible online learning.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'IIM Indore',
    learnPoints: salesMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/iim-indore/sales-and-marketing-executive-programme-iim-indore?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'rose',
    specialization: 'Sales & Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-parul-university-19',
    title: 'Online MBA Degree in Marketing – Parul University',
    description:
      'Online MBA programme in Marketing from Parul University. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'Parul University',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/parul-university/online-mba-degree-in-marketing-parul-university?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'green',
    specialization: 'Marketing',
    degreeType: 'masters',
  },
  {
    id: 'marketing-op-jindal-global-university-20',
    title: 'MBA in Marketing – O.P. Jindal Global University (JGU)',
    description:
      'Online MBA programme in Marketing from O.P. Jindal Global University. Designed for intermediate professionals seeking a UGC-entitled qualification with flexible online learning in marketing strategy and brand management.',
    duration: '2 Years',
    level: 'Intermediate',
    certificate: 'Degree',
    provider: 'O.P. Jindal Global University (JGU)',
    learnPoints: mastersMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/op-jindal-global-university/mba-in-marketing-op-jindal-global-university-jgu?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'amber',
    specialization: 'Marketing',
    degreeType: 'masters',
  },

  // —— Bachelor's programmes ——
  {
    id: 'marketing-nmims-bba-21',
    title: 'BBA in Marketing – NMIMS',
    description:
      'Online BBA programme in Marketing from NMIMS. Designed for undergraduate learners seeking a UGC-entitled bachelor’s qualification with flexible online learning in marketing strategy and brand management.',
    duration: '3 Years',
    level: 'Beginner',
    certificate: 'Degree',
    provider: 'NMIMS',
    learnPoints: bachelorsMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/nmims/bba-in-marketing?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'purple',
    specialization: 'Marketing',
    degreeType: 'bachelors',
  },
  {
    id: 'marketing-chandigarh-university-bba-22',
    title: 'Online BBA-Marketing – Chandigarh University',
    description:
      'Online BBA programme in Marketing from Chandigarh University. Designed for undergraduate learners seeking a UGC-entitled bachelor’s qualification with flexible online learning in marketing strategy and brand management.',
    duration: '3 Years',
    level: 'Beginner',
    certificate: 'Degree',
    provider: 'Chandigarh University',
    learnPoints: bachelorsMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/chandigarh-university/online-bbamarketing?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'rose',
    specialization: 'Marketing',
    degreeType: 'bachelors',
  },
  {
    id: 'marketing-manipal-university-jaipur-bba-23',
    title: 'Online BBA in Marketing – Manipal University Jaipur',
    description:
      'Online BBA programme in Marketing from Manipal University Jaipur. Designed for undergraduate learners seeking a UGC-entitled bachelor’s qualification with flexible online learning in marketing strategy and brand management.',
    duration: '3 Years',
    level: 'Beginner',
    certificate: 'Degree',
    provider: 'Manipal University Jaipur',
    learnPoints: bachelorsMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/manipal-university-jaipur/online-bba-in-marketing?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'orange',
    specialization: 'Marketing',
    degreeType: 'bachelors',
  },
  {
    id: 'marketing-dy-patil-university-pune-bba-24',
    title: 'Online BBA – Marketing Management – DY Patil University, Pune',
    description:
      'Online BBA programme in Marketing Management from DY Patil University, Pune. Designed for undergraduate learners seeking a UGC-entitled bachelor’s qualification with flexible online learning in marketing strategy and brand management.',
    duration: '3 Years',
    level: 'Beginner',
    certificate: 'Degree',
    provider: 'DY Patil University, Pune',
    learnPoints: bachelorsMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/dy-patil-university-pune/online-bba-marketing-management?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'cyan',
    specialization: 'Marketing Management',
    degreeType: 'bachelors',
  },
  {
    id: 'marketing-sharda-university-bba-25',
    title: 'BBA Marketing Management – Sharda University',
    description:
      'Online BBA programme in Marketing Management from Sharda University. Designed for undergraduate learners seeking a UGC-entitled bachelor’s qualification with flexible online learning in marketing strategy and brand management.',
    duration: '3 Years',
    level: 'Beginner',
    certificate: 'Degree',
    provider: 'Sharda University',
    learnPoints: bachelorsMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/sharda-university/bba-marketing-management-sharda-university?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'blue',
    specialization: 'Marketing Management',
    degreeType: 'bachelors',
  },
  {
    id: 'marketing-bennett-university-online-bba-26',
    title: 'BBA Marketing – Bennett University Online',
    description:
      'Online BBA programme in Marketing from Bennett University Online (Alliance University). Designed for undergraduate learners seeking a UGC-entitled bachelor’s qualification with flexible online learning in marketing strategy and brand management.',
    duration: '3 Years',
    level: 'Beginner',
    certificate: 'Degree',
    provider: 'Alliance University (Bennett University Online)',
    learnPoints: bachelorsMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/alliance-university/bba-marketing-bennett-university-online?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'violet',
    specialization: 'Marketing',
    degreeType: 'bachelors',
  },
  {
    id: 'marketing-alliance-university-bba-27',
    title: 'BBA Online in Marketing – Alliance University',
    description:
      'Online BBA programme in Marketing from Alliance University. Designed for undergraduate learners seeking a UGC-entitled bachelor’s qualification with flexible online learning in marketing strategy and brand management.',
    duration: '3 Years',
    level: 'Beginner',
    certificate: 'Degree',
    provider: 'Alliance University',
    learnPoints: bachelorsMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/alliance-university/bba-online-in-marketing-alliance-university?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'violet',
    specialization: 'Marketing',
    degreeType: 'bachelors',
  },
  {
    id: 'marketing-kl-university-bba-28',
    title: 'BBA Online Course in Marketing – KLU Online',
    description:
      'Online BBA programme in Marketing from KL University. Designed for undergraduate learners seeking a UGC-entitled bachelor’s qualification with flexible online learning in marketing strategy and brand management.',
    duration: '3 Years',
    level: 'Beginner',
    certificate: 'Degree',
    provider: 'KL University',
    learnPoints: bachelorsMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/kl-university/bba-online-course-in-marketing-klu-online?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'teal',
    specialization: 'Marketing',
    degreeType: 'bachelors',
  },
  {
    id: 'marketing-alliance-university-bcom-29',
    title: 'Online B.Com in Marketing Management – Alliance University',
    description:
      'Online B.Com programme in Marketing Management from Alliance University. Designed for undergraduate learners seeking a UGC-entitled bachelor’s qualification with flexible online learning in marketing strategy and brand management.',
    duration: '3 Years',
    level: 'Beginner',
    certificate: 'Degree',
    provider: 'Alliance University',
    learnPoints: bachelorsMarketingLearnPoints,
    riseuppUrl:
      'https://www.riseupp.com/degree-course/alliance-university/online-bcom-in-marketing-management-alliance-university?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'violet',
    specialization: 'Marketing Management',
    degreeType: 'bachelors',
  },

  // —— Doctorate programmes (DBA Marketing) ——
  {
    id: 'marketing-golden-gate-university-dba-30',
    title: 'DBA in Marketing – GGU',
    description:
      'Online DBA programme in Marketing from Golden Gate University. Designed for senior professionals seeking a doctoral-level qualification with flexible online learning in marketing leadership and research.',
    duration: '3 Years',
    level: 'Advanced',
    certificate: 'Degree',
    provider: 'Golden Gate University',
    learnPoints: [
      'Advance expertise in marketing strategy and brand leadership',
      'Apply research methods to complex marketing challenges',
      'Develop doctoral-level analytical and decision-making skills',
      'Build credentials for executive and academic marketing leadership roles',
    ],
    riseuppUrl:
      'https://www.riseupp.com/degree-course/golden-gate-university/dba-in-marketing-from-ggu?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'violet',
    specialization: 'Marketing',
    degreeType: 'doctorate',
  },
  {
    id: 'marketing-golden-gate-university-dba-31',
    title: 'DBA Specialization in Marketing – Golden Gate University',
    description:
      'Online DBA programme in Marketing from Golden Gate University. Designed for senior professionals seeking a doctoral-level qualification with flexible online learning in marketing leadership and research.',
    duration: '3 Years',
    level: 'Advanced',
    certificate: 'Degree',
    provider: 'Golden Gate University',
    learnPoints: [
      'Advance expertise in marketing strategy and brand leadership',
      'Apply research methods to complex marketing challenges',
      'Develop doctoral-level analytical and decision-making skills',
      'Build credentials for executive and academic marketing leadership roles',
    ],
    riseuppUrl:
      'https://www.riseupp.com/degree-course/golden-gate-university/dba-specialization-in-marketing-from-golden-gate-university?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'violet',
    specialization: 'Marketing',
    degreeType: 'doctorate',
  },
  {
    id: 'marketing-rushford-business-school-dba-32',
    title: 'DBA Specialization in Marketing – Rushford Business School',
    description:
      'Online DBA programme in Marketing from Rushford Business School. Designed for senior professionals seeking a doctoral-level qualification with flexible online learning in marketing leadership and research.',
    duration: '3 Years',
    level: 'Advanced',
    certificate: 'Degree',
    provider: 'Rushford Business School',
    learnPoints: [
      'Advance expertise in marketing strategy and brand leadership',
      'Apply research methods to complex marketing challenges',
      'Develop doctoral-level analytical and decision-making skills',
      'Build credentials for executive and academic marketing leadership roles',
    ],
    riseuppUrl:
      'https://www.riseupp.com/degree-course/rushford-business-school/dba-specialization-in-marketing?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'violet',
    specialization: 'Marketing',
    degreeType: 'doctorate',
  },
  {
    id: 'marketing-golden-gate-university-dba-immersion-33',
    title: 'DBA in Marketing (With Immersion) – GGU',
    description:
      'Online DBA programme in Marketing with immersion from Golden Gate University. Designed for senior professionals seeking a doctoral-level qualification with flexible online learning in marketing leadership and research.',
    duration: '3 Years',
    level: 'Advanced',
    certificate: 'Degree',
    provider: 'Golden Gate University',
    learnPoints: [
      'Advance expertise in marketing strategy and brand leadership',
      'Apply research methods to complex marketing challenges',
      'Develop doctoral-level analytical and decision-making skills',
      'Build credentials for executive and academic marketing leadership roles',
    ],
    riseuppUrl:
      'https://www.riseupp.com/degree-course/golden-gate-university/dba-in-marketing-with-immersion-from-ggu?ref=CP112',
    isFree: false,
    categories: ['marketing'],
    iconColor: 'violet',
    specialization: 'Marketing',
    degreeType: 'doctorate',
  },
];
